// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero_banner: dynamic(() => import("./HeroBanner")),
  product_showcase: dynamic(() => import("./ProductShowcase")),
  moving_stripe: dynamic(() => import("./MovingStripe")),
  comparison_section: dynamic(() => import("./ComparisonSection")),
  cta_banner: dynamic(() => import("./CTABanner")),
  ai_recommendations: dynamic(() => import("./AIRecommendations")),
  the_big_burner: dynamic(() => import("./TheBigBurner")),
  whatsnew: dynamic(() => import("./TheBigBurner")),
  the_shopping_grid: dynamic(() => import("./TheShoppingGrid")),
  the_moving_stripe: dynamic(() => import("./TheMovingStripe")),
  guide: dynamic(() => import("./Guide")),
};
